Alert progress
Nana2929/2023-formal-chemicloud pull request #13
Opened 2023-09-18 08:13 UTC by chongyi0717

2023-09-18 08:18 UTC, Nana2929 commented on README.md
> +python3 train.py --train_folder='dataset/train' --epoch=10 --model='bert-based-uncased' --output_model='output'
```
python3 train.py --train_folder='dataset/train' --epoch=10 --model='bert-base-uncased' --output_model='output'
```
This is the runnable version.

2023-09-18 08:25 UTC, Nana2929 commented on README.md
> +python3 predict.py --test_folder='dataset/test' --model='output' --predict_output_file='predictions'
The runnable version is
```
python3 predict.py --predict_folder='dataset/test' --model='output/checkpoint-2640-epoch-10' --predict_output_file='predictions' 
```
Suggestions:
- Change argument `model` to `checkpoint` to avoid confusion. `model` to me could more likely be a base model name or a `model` class architecture. 
- You should specify that after downloading from the google drive, how should the user change the argument name to make this runnable. For example, once `using_all_data` (weird name) is downloaded, the path should be modified to 
```
python3 predict.py --predict_folder='dataset/test' --model='using_all_data' --predict_output_file='predictions' 
```
- Change `using_all_data` drive name to something like `train_all_checkpoint`.

2023-09-18 08:32 UTC, Nana2929 commented on README.md
> +python3 split.py --dataset='dataset/all'
Quick question. 
It seems you have uploaded the data in `dataset` folder.
Then if I clone the repo, 
I can run all the commands without running `split.py`, correct? 

Add the following to the beginning of the section: 
#### 1. Splitting the Data
You can skip this section and directly use the prepared data in `dataset` folder. 
... 
#### 2. Training 
...

2023-09-18 08:33 UTC, Nana2929 commented on README.md
> +- F1 macro avg = 0.89
F1 macro avg across 5 folds: 0.89

2023-09-18 08:35 UTC, Nana2929 commented on train.py
> +                num_train_epochs=NUM_EPOCH,
Weird that you have set this and only this to all capital. Is there a reason?

2023-09-18 08:37 UTC, Nana2929 commented on predict.py
> +    df = df[['content_text']]
Add in README that the given file for prediction should contain the column `content_text`, which will be used as the text for inference.

2023-09-18 08:38 UTC, Nana2929 commented on requirements.txt
> +torch==2.1.0.dev20230530+cu121
Sometimes adding version leads to many other issues. 
Two options:
1. Add in readme that versions here are for reference, true versions actually depend on their machine; or it is likely that the latest will work well. 
2. Remove the versions in this file.

2023-09-18 08:43 UTC, Nana2929 requested changes
Code runs successfully after slight alteration of commands. 
See my comments.

2023-09-18 09:00 UTC, chongyi0717 commented on README.md
> +python3 predict.py --test_folder='dataset/test' --model='output' --predict_output_file='predictions'
它的格式是會產生outputs然後如果有多少個epoch裡面就有多少個checkpoint
除了checkpoint之外還會默認把最好的放在最外面
所以用outputs的話拿的就是最好的checkpoint

2023-09-18 09:04 UTC, chongyi0717 commented on README.md
> +- F1 macro avg = 0.89
這個不是5-fold的，而是直接拿另一個只用80% 資料來訓練的模型來測試
只是很神奇地跟5-fold的平均分數一樣

2023-09-18 09:05 UTC, chongyi0717 commented on train.py
> +                num_train_epochs=NUM_EPOCH,
是要不用NUM_EPOCH而是直接用args.epoch這樣嗎？

2023-09-18 16:48 UTC, chongyi0717 commented on README.md
> +python3 split.py --dataset='dataset/all'
這個部分在24&25行有提到，可能是不太明顯

2023-09-19 05:44 UTC, Nana2929 approved these changes

2023-09-19 05:44 UTC, merged